import listImages from "../Images"
export const listMembers = [
    {
        id:0,
      name: 'Monkey D.Luffy',
      ngaySinh: '01/01/1998',
      ngayVaoCongTy: '09/08/2021',
      phongBan: 'CEO',
      ngayNghiHienCo: '4',
      ngayDaLamThem: '5',
      Image: listImages.luffyImage,
      maNhanVien: 1,
      salaryScale: 1
    },
    {
        id:1,
      name: 'Nami',
      ngaySinh: '11/08/1998',
      ngayVaoCongTy: '09/08/2021',
      phongBan: 'IT',
      ngayNghiHienCo: '7',
      ngayDaLamThem: '9',
      Image: listImages.namiImage,
      maNhanVien: 1,
      salaryScale: 1
    },
    {
        id:2,
      name: 'Nico Robin',
      ngaySinh: '15/09/1998',
      ngayVaoCongTy: '25/08/2021',
      phongBan: 'Design',
      ngayNghiHienCo: '1',
      ngayDaLamThem: '6',
      Image: listImages.robinImage,
      maNhanVien: 1,
      salaryScale: 1
    },
    {
        id:3,
      name: 'Vinsmoke Sanji',
      ngaySinh: '17/07/2002',
      ngayVaoCongTy: '15/02/2022',
      phongBan: 'CEO',
      ngayNghiHienCo: '3',
      ngayDaLamThem: '6',
      Image: listImages.sanjiImage,
      maNhanVien: 1,
      salaryScale: 1
    },
    {
        id:4,
      name: 'Zoro',
      ngaySinh: '24/05/2001',
      ngayVaoCongTy: '16/02/2019',
      phongBan: 'Brse',
      ngayNghiHienCo: '4',
      ngayDaLamThem: '5',
      Image: listImages.zoroImage,
      maNhanVien: 1,
      salaryScale: 1
    },
    {
        id:5,
        name: 'Yamato',
        ngaySinh: '24/05/2001',
        ngayVaoCongTy: '16/02/2019',
        phongBan: 'Brse',
        ngayNghiHienCo: '4',
        ngayDaLamThem: '5',
        Image: listImages.yamatoImage,
        maNhanVien: 1,
        salaryScale: 1
    },
    {
        id:6,
      name: 'Monkey D.Luffy',
      ngaySinh: '01/01/1998',
      ngayVaoCongTy: '09/08/2021',
      phongBan: 'IT',
      ngayNghiHienCo: '4',
      ngayDaLamThem: '5',
      Image: listImages.luffyImage,
      maNhanVien: 1,
      salaryScale: 1
    },
    {
        id:7,
      name: 'Nami',
      ngaySinh: '11/08/1998',
      ngayVaoCongTy: '09/08/2021',
      phongBan: 'IT',
      ngayNghiHienCo: '7',
      ngayDaLamThem: '9',
      Image: listImages.namiImage,
      maNhanVien: 1,
      salaryScale: 1
    },
    {
        id:8,
      name: 'Nico Robin',
      ngaySinh: '15/09/1998',
      ngayVaoCongTy: '25/08/2021',
      phongBan: 'Design',
      ngayNghiHienCo: '1',
      ngayDaLamThem: '6',
      Image: listImages.robinImage,
      maNhanVien: 1,
      salaryScale: 1
    },
    {
        id:9,
      name: 'Vinsmoke Sanji',
      ngaySinh: '17/07/2002',
      ngayVaoCongTy: '15/02/2022',
      phongBan: 'Tester',
      ngayNghiHienCo: '3',
      ngayDaLamThem: '6',
      Image: listImages.sanjiImage,
      maNhanVien: 1,
      salaryScale: 1
    },
    {
        id:10,
      name: 'Zoro',
      ngaySinh: '24/05/2001',
      ngayVaoCongTy: '16/02/2019',
      phongBan: 'CEO',
      ngayNghiHienCo: '4',
      ngayDaLamThem: '5',
      Image: listImages.zoroImage,
      maNhanVien: 1,
      salaryScale: 1
    },
    {
        id:11,
        name: 'Yamato',
        ngaySinh: '24/05/2001',
        ngayVaoCongTy: '16/02/2019',
        phongBan: 'Brse',
        ngayNghiHienCo: '4',
        ngayDaLamThem: '5',
        Image: listImages.yamatoImage,
        maNhanVien: 1,
        salaryScale: 1
    },
    {
        id:12,
      name: 'Monkey D.Luffy',
      ngaySinh: '01/01/1998',
      ngayVaoCongTy: '09/08/2021',
      phongBan: 'IT',
      ngayNghiHienCo: '4',
      ngayDaLamThem: '5',
      Image: listImages.luffyImage,
      maNhanVien: 1,
      salaryScale: 1
    },
    {
        id:13,
      name: 'Nami',
      ngaySinh: '11/08/1998',
      ngayVaoCongTy: '09/08/2021',
      phongBan: 'IT',
      ngayNghiHienCo: '7',
      ngayDaLamThem: '9',
      Image: listImages.namiImage,
      maNhanVien: 1,
      salaryScale: 1
    },
    {
        id:14,
      name: 'Nico Robin',
      ngaySinh: '15/09/1998',
      ngayVaoCongTy: '25/08/2021',
      phongBan: 'Design',
      ngayNghiHienCo: '1',
      ngayDaLamThem: '6',
      Image: listImages.robinImage,
      maNhanVien: 1,
      salaryScale: 1
    },
    {
        id:15,
      name: 'Vinsmoke Sanji',
      ngaySinh: '17/07/2002',
      ngayVaoCongTy: '15/02/2022',
      phongBan: 'Tester',
      ngayNghiHienCo: '3',
      ngayDaLamThem: '6',
      Image: listImages.sanjiImage,
      maNhanVien: 1,
      salaryScale: 1
    },
    {
        id:16,
      name: 'Zoro',
      ngaySinh: '24/05/2001',
      ngayVaoCongTy: '16/02/2019',
      phongBan: 'Brse',
      ngayNghiHienCo: '4',
      ngayDaLamThem: '5',
      Image: listImages.zoroImage,
      maNhanVien: 1,
      salaryScale: 1
    },
    {
        id:17,
        name: 'Yamato',
        ngaySinh: '24/05/2001',
        ngayVaoCongTy: '16/02/2019',
        phongBan: 'Brse',
        ngayNghiHienCo: '4',
        ngayDaLamThem: '5',
        Image: listImages.yamatoImage,
        maNhanVien: 1,
        salaryScale: 1
    }
    
]